### ISSUE TITLE
Evaluate tests dependency on dnx

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#107]
## Expected
Tests that publish and run projects succeed, and execute well.

## Observed
These tests deploy via `dnu.cmd` and execute via `dnx.exe`. We're depending on dnx being installed in the build machine, but dnx is currently not there. The appveyor build logs show this error:

```
[00:09:20]     Production_Startup [Variation: StarterMvc_ProductionScenario] [Stage: Collection] [Iteration: 9/10] [FAIL]
[00:09:20] 
[00:09:20]       System.InvalidOperationException : Cannot start process because a file name has not been provided.
[00:09:20] 
[00:09:20]       Stack Trace:
[00:09:20] 
[00:09:20]            at System.Diagnostics.Process.Start()
[00:09:20] 
[00:09:20]            at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
[00:09:20] 
[00:09:20]         C:\projects\performance\src\Benchmarks.Utility\Helpers\DnxHelper.cs(55,0): at Benchmarks.Utility.Helpers.DnxHelper.Restore(String workingDir, String framework, Boolean quiet)
[00:09:20] 
[00:09:20]         C:\projects\performance\src\Benchmarks.Utility\Helpers\SampleManager.cs(140,0): at Benchmarks.Utility.Helpers.SampleManager.DnxPublishedSample.doInitialization()
[00:09:20] 
[00:09:20]         C:\projects\performance\src\Benchmarks.Utility\Helpers\SampleManager.cs(84,0): at Benchmarks.Utility.Helpers.SampleManager.SampleEntry.Initialize()
[00:09:20] 
[00:09:20]         C:\projects\performance\src\Benchmarks.Utility\Helpers\SampleManager.cs(31,0): at Benchmarks.Utility.Helpers.SampleManager.GetDnxPublishedSample(String name, String framework)
[00:09:20] 
[00:09:20]         C:\projects\performance\test\Microsoft.AspNetCore.Tests.Performance\WebPerformance.cs(61,0): at Microsoft.AspNetCore.Tests.Performance.WebPerformance.Production_Startup(String sampleName)
```

Basically what's happening is that class `Benchmarks.Utility.Helpers.DnxHelper` attempts to find `dnu.cmd` and `dnx.exe`, and if it can't find them it silently returns `null` and proceeds to execute it regardless. In computers where both clr and coreclr runtimes of dnx are installed these tests execute normally.

## Solutions
We have three ways here:
  1. Fix the tests to not depend on dnx, or
  2. Disable these tests, or
  3. Install dnx (both clr and coreclr) as part of the build.

The most reasonable one is fixing the tests, unless they're not needed.

**Comment by DavidObando** [comment]
Addressed by #133
