### ISSUE TITLE
Build gets stuck in OSX and Linux

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#134]
During the execution of the `Microsoft.AspNetCore.Tests.Performance` tests, we get errors like this:
```
info: BasicKestrel.CoreCLR.Production_DotNet_Startup[0]
      Test project is set up at /var/folders/pl/51wck33d0s33knk128xs5q000000gn/T/tmpPigFAm.tmp/BasicKestrel
    GracefulExit [Variation: BasicKestrel_DotNet_ProductionScenario] [Stage: Collection] [Iteration: 10/10] [FAIL]
      System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)
      ---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
      -------- System.Net.Http.CurlException : Couldn't connect to server
      Stack Trace:
           at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
           at Microsoft.AspNetCore.Tests.Performance.WebPerformance.GracefulExit(String sampleName)
        ----- Inner Stack Trace -----
        
        ----- Inner Stack Trace -----
           at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
           at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(EasyRequest completedOperation, CURLcode messageResult)
```

The test then finishes and shows the summary:
```
=== TEST EXECUTION SUMMARY ===
   Microsoft.AspNetCore.Tests.Performance  Total: 63, Errors: 0, Failed: 52, Skipped: 1, Time: 15.477s
```

The `dotnet test` process remains alive. The Activity Monitor shows that there's another instance of `dotnet` currently serving the `BasicKestrel` test from a temporary directory, indicating that the failed test should have been able to send the request and connect to the server. Additionally, the test isn't able to kill the process tree after it's done.

This is related to #101, except this time it appears to have been fixed for Windows.

**Comment by DavidObando** [comment]
Fixed by #139.
