### ISSUE TITLE
Investigate occasional EBUSY failures during Microbenchmarks.Tests

### ISSUE THREAD

**Issue by dougbu** [aspnet/Performance#209]
Every few runs of Microbenchmarks.Tests fail with the following output:
```
EXEC : error : [xUnit.net 00:00:20.7179002]     MainToConfigureOverhead(variationServer: "Microsoft.AspNetCore.Server.HttpSys") [Stage: Collection] [Iteration: 45/100] [FAIL] [C:\dd\dnx\Universe\Performance\.build\makefile.proj]
  Information: [xUnit.net 00:00:20.7199451]       System.AggregateException : One or more errors occurred. (Error -4082 EBUSY resource busy or locked)
  Information: [xUnit.net 00:00:20.7201390]       ---- Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException : Error -4082 EBUSY resource busy or locked
  Information: [xUnit.net 00:00:20.7216130]       Stack Trace:
  Information: [xUnit.net 00:00:20.7235772]            at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
  Information: [xUnit.net 00:00:20.7237916]            at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
  Information: [xUnit.net 00:00:20.7238971]            at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Dispose()
  Information: [xUnit.net 00:00:20.7240043]            at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Dispose()
  Information: [xUnit.net 00:00:20.7241013]            at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
  Information: [xUnit.net 00:00:20.7241937]            at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
  Information: [xUnit.net 00:00:20.7243243]         C:\dd\dnx\Universe\Performance\test\Microbenchmarks.Tests\HostingTests.cs(42,0): at Microbenchmarks.Tests.HostingTests.MainToConfigureOverhead(String variationServer)
  Information: [xUnit.net 00:00:20.7248360]         ----- Inner Stack Trace -----
  Information: [xUnit.net 00:00:20.7249496]            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.ThrowError(Int32 statusCode)
  Information: [xUnit.net 00:00:20.7250530]            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_close(UvLoopHandle handle)
  Information: [xUnit.net 00:00:20.7251528]            at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.ReleaseHandle()
  Information: [xUnit.net 00:00:20.7252458]            at System.Runtime.InteropServices.SafeHandle.InternalDispose()
  Information: [xUnit.net 00:00:20.7253453]            at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
  Information: [xUnit.net 00:00:20.7254260]         --- End of stack trace from previous location where exception was thrown ---
  Information: [xUnit.net 00:00:20.7255198]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  Information: [xUnit.net 00:00:20.7256178]            at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.<StopAsync>d__51.MoveNext()
```

The above occurred while `Calibration_100ms()`, `TagHelperResolution(designTime: True)`, and `MainToConfigureOverhead(variationServer: "Microsoft.AspNetCore.Server.HttpSys")` tests were running in parallel in a .NET Core run. I'm not sure whether EBUSY errors are specific to this part of the run. Might occur during desktop runs as well.

**Comment by halter73** [comment]
This seems like a dup of https://github.com/aspnet/KestrelHttpServer/issues/1231. Thanks for identifying another scenario where this occurs.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
