### ISSUE TITLE
Concurrency issue in benchmark result processor

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#64]
During a local build I saw this:

```
System.NotSupportedException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Benchmarks.Framework.BenchmarkPersistence.SqlServerBenchmarkResultProcessor.SaveSummary(BenchmarkRunSummary summary) in D:\GitHub\aspnet\Performance\src\Benchmarks.Framework\BenchmarkPersistence\SqlServerBenchmarkResultProcessor.cs:line 55
   at Benchmarks.Framework.BenchmarkPersistence.BenchmarkResultProcessor.SaveSummary(BenchmarkRunSummary summary) in D:\GitHub\aspnet\Performance\src\Benchmarks.Framework\BenchmarkPersistence\BenchmarkResultProcessor.cs:line 35
   at Benchmarks.Framework.BenchmarkTestCaseRunner.<RunTestAsync>d__7.MoveNext() in D:\GitHub\aspnet\Performance\src\Benchmarks.Framework\BenchmarkTestCaseRunner.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
```

It's pretty obvious now that we didn't account for concurrent uses of the cached EF contexts. Working on a fix now.

**Comment by DavidObando** [comment]
Fixed with 8a3685e.
