### ISSUE TITLE
DotnetPublish throws exception in Linux

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#85]
**This issue requires more investigation**

There's an issue, probably with the `Benchmarks.Utility` code, which causes an exception during execution of the DotnetPublish test.

```
    DotnetPublish [Variation: DotnetPublish_StarterMvc] [Stage: Collection] [Iteration: 5/5] [FAIL]
      System.ComponentModel.Win32Exception : No such file or directory
      Stack Trace:
           at System.Diagnostics.Process.ResolvePath(String filename)
           at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
           at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
           at Benchmarks.Utility.Helpers.CommandLineRunner.Execute(String arguments, String workingDirectory)
           at Benchmarks.Utility.Helpers.CommandLineRunner.Execute(String arguments)
           at Benchmarks.Utility.Helpers.SampleManager.RestoredSample.doInitialization()
           at Benchmarks.Utility.Helpers.SampleManager.SampleEntry.Initialize()
           at Benchmarks.Utility.Helpers.SampleManager.GetRestoredSample(String name)
           at Microsoft.AspNetCore.Tests.Performance.PublishTests.DotnetPublish(String sampleName)
```

**Comment by SajayAntony** [comment]
@shhsu @brianrob is this the issue you guys hit today?

**Comment by shhsu** [comment]
Looks different
There was an assembly not found exception with System.Reflection.Metadata
I was unable to repro on my asp-xhpc6

**Comment by DavidObando** [comment]
@shhsu what OS were you using when you saw this? Is the error gone now?

**Comment by shhsu** [comment]
Ubuntu 14.04
I was unable to repro the issue on an existing server asp-xhpc6 and a fresh linux installation from my hyper-v.
It might be something specific to that particular lab machine which I do not have access to currently.

**Comment by SajayAntony** [comment]
@DavidObando  which test did you try to publish?

**Comment by DavidObando** [comment]
@SajayAntony It was the DotnetPublish_StarterMvc during `build.cmd`. It was preventing a clean build, but I haven't seen the travis log in a few days. I'll check it later today. I believe this wasn't the only test error.

**Comment by DavidObando** [comment]
Closing, not repro anymore.
