### ISSUE TITLE
Two hours into a reliability test run: The timeout period elapsed prior to obtaining a connection from the pool

### ISSUE THREAD

**Issue by sivagms** [aspnet/Performance#88]
Scenario:
       Linux: Nginx + Core
       Windows: IIS + Core

       Server: Azure Standard A2 VM
       Client: Azure Standard A2 VM 
       Server and Client in an Isolated Subnet

       Music Store Home Page with no cache - Every request goes to database
       SQL Azure Database - Standard S3  - Usage 10%

       Linux - 69 connections/sec
       Windows - 20 connections/sec

       500 virtual clients
       No Keep-Alive
       Target 75%  CPU Usage
       Duration 24 hours and 120 hours

Linux 24 hour run:  Holding up at  99.990% reliability so far -  75% CPU, 540MB memory, 69 connections/sec, 69 requests/sec, Avg Latency 7155ms.

Windows 24 hour run: Stopped responding after about 2 hours due to connection pool issue with SQL with just 19 connections/sec - 76k mem,  80% CPU, 1.22GB memory, 19 req/sec, Avg Latency 25493ms

---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.) ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerableExtensions.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
---> (Inner Exception #0) System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()<---

/cc @taoliseki

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
